name: Fetch Articles Cron

on:
  schedule:
    - cron: '0 */6 * * *' # 6時間ごと（1日4回）
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run fetch.ts
        run: npx ts-node fetch/fetch.ts

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/articles.json
          git diff --cached --quiet || git commit -m 'chore: update articles.json [cron]'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 